import { Inter } from "next/font/google";
import "./globals.css";
import "@rainbow-me/rainbowkit/styles.css";
// Import styles of packages that you've installed.
// All packages except `@mantine/hooks` require styles imports
import "@mantine/core/styles.css";

import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import { AppShellProvider } from "@/components/AppShell";
import { Providers } from "./providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <head>
                <ColorSchemeScript />
            </head>
            <body className={inter.className}>
                {" "}
                <Providers>
                    <MantineProvider>
                        <AppShellProvider>{children}</AppShellProvider>
                    </MantineProvider>
                </Providers>
            </body>
        </html>
    );
}
